
# -------------------------------------------------------------------------
# See: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# -------------------------------------------------------------------------
@target-url=http://127.0.0.1:9999

# -------------------------------------------------------------------------
### Blind check of 'target-url'
# -------------------------------------------------------------------------
curl {{target-url}}/

### GET the test route
curl {{target-url}}/api

### Get HTMX version
POST {{target-url}}/test
accpet: text/html
content-type: application/json
hx-request: true
hx-trigger-name: main

{
    "task": "build"
}


### Get HTMX version
GET {{target-url}}/test
hx-request: true
hx-trigger-name: main
accpet: application/json

### Get as YAML contents
GET {{target-url}}/test
accept: application/yaml

### Get as CSV content
GET {{target-url}}/test
accept: text/csv,application/json
