
# -------------------------------------------------------------------------
# See: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# -------------------------------------------------------------------------
@target-url=http://127.0.0.1:9999

# -------------------------------------------------------------------------
### Blind check of 'target-url'
# -------------------------------------------------------------------------
curl {{target-url}}/

### Test if the API status is returned
curl {{target-url}}/api


### Check for custom route
curl {{target-url}}/ping


### Check for custom route
curl {{target-url}}/todo/

### Get hetml formatted
GET {{target-url}}/todo/
Hx-Request: true
accpet: text/html

### Get YAML content
GET {{target-url}}/todo/list
accept: application/yaml

### Get as CSV content
GET {{target-url}}/todo/list
accept: text/csv
