name: Build Artifacts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Taskfile support
        uses: arduino/setup-task@v1
          
      - name: Build Artifacts
        run: task build
