name: Build Artifacts

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Taskfile support
        uses: arduino/setup-task@v1
          
      - name: Build Artifacts
        run: task build

      - name: Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE.txt